module.exports = {
  th: {
    skipToContent: 'ข้ามไปที่เนื้อหา',
    navMain: 'เมนูหลัก',
    navBlog: 'บทความ',
    navProjects: 'โปรเจกต์',
    navAbout: 'เกี่ยวกับ',
    switchLang: 'English',
    themeToggle: 'สลับธีมสว่างหรือมืด',
    errorNotFoundTitle: 'ไม่พบหน้านี้',
    errorNotFoundBody: 'ลิงก์อาจพิมพ์ผิด หรือหน้านี้ถูกลบไปแล้ว',
    errorBadRequestTitle: 'ลิงก์ไม่ถูกต้อง',
    errorBadRequestBody: 'ลิงก์นี้อาจขาดหายระหว่างการแชร์ ลองเปิดจากหน้ารวมบทความแทน',
    errorServerTitle: 'เกิดข้อผิดพลาด',
    errorServerBody: 'ระบบขัดข้องชั่วคราว ลองใหม่อีกครั้งในอีกสักครู่',
    errorBackToBlog: 'ไปหน้ารวมบทความ',
    errorBackHome: 'กลับหน้าแรก',
    latestPosts: 'บทความล่าสุด',
    allPosts: 'ดูบทความทั้งหมด',
    noPosts: 'ยังไม่มีบทความ',
    badgeOtherLang: 'ภาษาอังกฤษ',
    postTags: 'แท็ก',
    backToBlog: 'กลับไปหน้ารวมบทความ',
    pagination: 'การแบ่งหน้า',
    pageLabel: 'หน้า',
    pageNewer: 'บทความใหม่กว่า',
    pageOlder: 'บทความเก่ากว่า'
  },
  en: {
    skipToContent: 'Skip to content',
    navMain: 'Main',
    navBlog: 'Blog',
    navProjects: 'Projects',
    navAbout: 'About',
    switchLang: 'ไทย',
    themeToggle: 'Toggle light or dark theme',
    errorNotFoundTitle: 'Page not found',
    errorNotFoundBody: 'The link may be mistyped, or the page has been removed.',
    errorBadRequestTitle: 'Invalid link',
    errorBadRequestBody: 'This link may have been cut off when it was shared. Try opening it from the blog index instead.',
    errorServerTitle: 'Something went wrong',
    errorServerBody: 'The site hit a temporary problem. Please try again in a moment.',
    errorBackToBlog: 'Go to the blog',
    errorBackHome: 'Back to home',
    latestPosts: 'Latest posts',
    allPosts: 'All posts',
    noPosts: 'No posts yet.',
    badgeOtherLang: 'Thai',
    postTags: 'Tags',
    backToBlog: 'Back to the blog',
    pagination: 'Pagination',
    pageLabel: 'Page',
    pageNewer: 'Newer posts',
    pageOlder: 'Older posts'
  }
};
