module.exports = {
  th: {
    skipToContent: 'ข้ามไปที่เนื้อหา',
    navMain: 'เมนูหลัก',
    navBlog: 'บทความ',
    navProjects: 'โปรเจกต์',
    navAbout: 'เกี่ยวกับ',
    switchLang: 'English',
    themeToggle: 'สลับธีมสว่างหรือมืด',
    errorNotFoundTitle: 'ไม่พบหน้านี้',
    errorNotFoundBody: 'ลิงก์อาจพิมพ์ผิด หรือหน้านี้ถูกลบไปแล้ว',
    errorBadRequestTitle: 'ลิงก์ไม่ถูกต้อง',
    errorBadRequestBody: 'ลิงก์นี้อาจขาดหายระหว่างการแชร์ ลองเปิดจากหน้ารวมบทความแทน',
    errorServerTitle: 'เกิดข้อผิดพลาด',
    errorServerBody: 'ระบบขัดข้องชั่วคราว ลองใหม่อีกครั้งในอีกสักครู่',
    errorBackToBlog: 'ไปหน้ารวมบทความ',
    errorBackHome: 'กลับหน้าแรก',
    latestPosts: 'บทความล่าสุด',
    allPosts: 'ดูบทความทั้งหมด',
    noPosts: 'ยังไม่มีบทความ',
    badgeOtherLang: 'ภาษาอังกฤษ',
    postTags: 'แท็ก',
    // {n} is the estimated number of minutes from src/reading-time.js
    readTime: 'อ่าน {n} นาที',
    backToBlog: 'กลับไปหน้ารวมบทความ',
    pagination: 'การแบ่งหน้า',
    pageLabel: 'หน้า',
    pageNewer: 'บทความใหม่กว่า',
    pageOlder: 'บทความเก่ากว่า',
    featuredProjects: 'โปรเจกต์เด่น',
    allProjects: 'ดูโปรเจกต์ทั้งหมด',
    noProjects: 'ยังไม่มีโปรเจกต์',
    projectRepo: 'ซอร์สโค้ด',
    projectDemo: 'ดูเดโม',
    backToProjects: 'กลับไปหน้ารวมโปรเจกต์',
    tagTitle: 'บทความที่ติดแท็ก',
    searchTitle: 'ค้นหา',
    searchLabel: 'คำค้นหา',
    searchButton: 'ค้นหา',
    searchHint: 'พิมพ์อย่างน้อย 2 ตัวอักษรเพื่อค้นหา',
    searchProjectsHeading: 'โปรเจกต์ที่พบ',
    searchPostsHeading: 'บทความที่พบ',
    searchNoResults: 'ไม่พบผลลัพธ์สำหรับ',
    aboutGreeting: 'สวัสดี ฉันชื่อ',
    aboutColorsLabel: 'สีที่ฉันชอบ:',
    aboutContactLabel: 'ติดต่อ:',
    aboutVideoTitle: 'รู้จักฉันมากขึ้น',
    navPrivacy: 'ความเป็นส่วนตัว',
    privacyCookieHeading: 'คุกกี้ที่เว็บนี้ใช้',
    privacyContactLabel: 'ติดต่อ',
    privacyResetButton: 'ตั้งค่า cookie ใหม่',
    cookieColName: 'ชื่อ',
    cookieColSetBy: 'ตั้งโดย',
    cookieColLifetime: 'อายุ',
    cookieColPurpose: 'ใช้ทำอะไร',
    cookieColCategory: 'ประเภท',
    cookieLifetime30d: '30 วัน',
    cookieLifetime1y: '1 ปี',
    cookieLifetime180d: '180 วัน',
    cookieLifetime2y: '2 ปี',
    cookieLifetimeNone: 'ไม่หมดอายุ',
    cookiePurposeAdmin: 'login ของผู้ดูแล ส่งเฉพาะ path /admin',
    cookiePurposeLang: 'จำภาษาล่าสุดที่อ่าน ใช้ตอนเข้า /',
    cookiePurposeConsent: 'จำว่าผู้อ่านยอมรับหรือปฏิเสธ cookie สถิติ',
    cookiePurposeGa: 'สถิติผู้เข้าชม มีเฉพาะหลังผู้อ่านกดยอมรับ',
    cookiePurposeTheme: 'จำธีมสว่างหรือมืด ไม่ถูกส่งไป server',
    cookieCategoryNecessary: 'จำเป็น',
    cookieCategoryFunctional: 'จำเป็นต่อการทำงาน',
    cookieCategoryAnalytics: 'สถิติ ต้องได้รับความยินยอม',
    consentAriaLabel: 'แถบแจ้งเรื่องคุกกี้',
    consentTextAnalytics: 'เว็บนี้ขอใช้คุกกี้เพื่อวัดผลการเข้าชมแบบไม่ระบุตัวตน อ่านรายละเอียดที่',
    consentTextEssential: 'เว็บนี้ใช้เฉพาะคุกกี้ที่จำเป็นต่อการทำงาน อ่านรายละเอียดที่',
    consentPrivacyLink: 'หน้าความเป็นส่วนตัว',
    consentAccept: 'ยอมรับ',
    consentReject: 'ปฏิเสธ',
    consentAcknowledge: 'รับทราบ'
  },
  en: {
    skipToContent: 'Skip to content',
    navMain: 'Main',
    navBlog: 'Blog',
    navProjects: 'Projects',
    navAbout: 'About',
    switchLang: 'ไทย',
    themeToggle: 'Toggle light or dark theme',
    errorNotFoundTitle: 'Page not found',
    errorNotFoundBody: 'The link may be mistyped, or the page has been removed.',
    errorBadRequestTitle: 'Invalid link',
    errorBadRequestBody: 'This link may have been cut off when it was shared. Try opening it from the blog index instead.',
    errorServerTitle: 'Something went wrong',
    errorServerBody: 'The site hit a temporary problem. Please try again in a moment.',
    errorBackToBlog: 'Go to the blog',
    errorBackHome: 'Back to home',
    latestPosts: 'Latest posts',
    allPosts: 'All posts',
    noPosts: 'No posts yet.',
    badgeOtherLang: 'Thai',
    postTags: 'Tags',
    // {n} is the estimated number of minutes from src/reading-time.js
    readTime: '{n} min read',
    backToBlog: 'Back to the blog',
    pagination: 'Pagination',
    pageLabel: 'Page',
    pageNewer: 'Newer posts',
    pageOlder: 'Older posts',
    featuredProjects: 'Featured projects',
    allProjects: 'All projects',
    noProjects: 'No projects yet.',
    projectRepo: 'Source code',
    projectDemo: 'Live demo',
    backToProjects: 'Back to projects',
    tagTitle: 'Posts tagged',
    searchTitle: 'Search',
    searchLabel: 'Search term',
    searchButton: 'Search',
    searchHint: 'Type at least 2 characters to search.',
    searchProjectsHeading: 'Matching projects',
    searchPostsHeading: 'Matching posts',
    searchNoResults: 'No results for',
    aboutGreeting: "Hello, I'm",
    aboutColorsLabel: 'My favorite colors:',
    aboutContactLabel: 'Contact:',
    aboutVideoTitle: 'Get to know me',
    navPrivacy: 'Privacy',
    privacyCookieHeading: 'Cookies this site uses',
    privacyContactLabel: 'Contact',
    privacyResetButton: 'Update cookie settings',
    cookieColName: 'Name',
    cookieColSetBy: 'Set by',
    cookieColLifetime: 'Lifetime',
    cookieColPurpose: 'Purpose',
    cookieColCategory: 'Category',
    cookieLifetime30d: '30 days',
    cookieLifetime1y: '1 year',
    cookieLifetime180d: '180 days',
    cookieLifetime2y: '2 years',
    cookieLifetimeNone: 'Never expires',
    cookiePurposeAdmin: 'Admin login, sent only on path /admin',
    cookiePurposeLang: 'Remembers the last language read, used when visiting /',
    cookiePurposeConsent: 'Remembers whether the reader accepted or rejected analytics cookies',
    cookiePurposeGa: 'Visitor statistics, set only after the reader accepts',
    cookiePurposeTheme: 'Remembers light or dark theme, never sent to the server',
    cookieCategoryNecessary: 'Necessary',
    cookieCategoryFunctional: 'Necessary for the site to work',
    cookieCategoryAnalytics: 'Analytics, requires consent',
    consentAriaLabel: 'Cookie notice',
    consentTextAnalytics: 'This site would like to use cookies to measure anonymous visits. Read more on the',
    consentTextEssential: 'This site only uses cookies necessary for it to work. Read more on the',
    consentPrivacyLink: 'privacy page',
    consentAccept: 'Accept',
    consentReject: 'Reject',
    consentAcknowledge: 'Acknowledge'
  }
};
